<?php


class Controller_Login extends Controller
{
    function action_index()
    {
        if(isset($_POST['submit'])){
            /**
             * Array ( 
             *  [email] => test@test.ru 
             *  [password] => 1 
             *  [submit] => 
             * )
             */
            $test = Class_Test_Acces::test($_POST['email'], $_POST['password']);
            if(!$test){
                Class_Alert_Message::error("Неверный логин или пароль");
                setcookie("id_user", '', time() - 2592000,'/');
                setcookie("hash_key", '', time() - 2592000,'/');
                header("Location: ".DOCUMENT_ROOT.DS."login");
                exit;
            }
            $this->model->rolees_id = $test;
            header('Location: '.DOCUMENT_ROOT.'/');
            exit();
        }
        parent::action_index(); // TODO: Change the autogenerated stub
        $data['title']         = "Вход";
        $this->view->generate('login_view.php', 'page.php', $data);
    }
}