<?php


class Controller_Login extends Controller
{
    function action_index()
    {
        parent::action_index(); // TODO: Change the autogenerated stub
        $data['title']         = "Вход";
        $this->view->generate('login_view.php', 'index.php', $data);
    }
}